### ISSUE TITLE
translation is portuguese.json is completed

### ISSUE THREAD

**Issue by bielribeiro18** [Timtam/yugioh-soundpack#15]
Expensive toni.

I have to warn you that the sound file has been translated into Portuguese.

How 
[portuguese.json.txt](https://github.com/Timtam/yugioh-soundpack/files/2683089/portuguese.json.txt)

hugs.

**Comment by Timtam** [comment]
Added, seems incomplete though, some triggers occurred multiple times and therefore got deleted. Some initialization triggers are missing as well. I'd suggest you read into the mcl file first next time to get an understanding about how the system works.
I'd recommend to fork this repository correctly, apply your changes, test if they work and submit a pull request afterwards.

**Comment by Timtam** [comment]
ca18ba395e10e4de5ba595959f2821a6b6a89375
